homepage:
    resource: "@AppToyotaBundle/Resources/config/routing/main.yml"
    prefix:   / 

app_toyota:
    resource: "@AppToyotaBundle/Resources/config/routing.yml"
    prefix:   /
    
app_toyota_hello:
    resource: "@AppToyotaBundle/Resources/config/routing/hello.yml"
    prefix:   /    
    
    
